name: daVinci-local-infra

services:
  redis:
    image: redis:7.2
    container_name: daVinci-redis
    ports:
      - "6379:6379"
    volumes:
      - daVinci-redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 30s
      retries: 3

volumes:
  daVinci-redis-data:
