name: Deploy Backend to NCP

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          cd deploy 
          cp ~/deploy/.env ./.env

          if [ ! -f .env ]; then
            echo ".env file not exists"
            exit 1
          fi 

          echo ".env file copied."

      - name: Build and deploy with Docker Compose
        run: |
          cd deploy
          docker compose down
          docker compose up -d --build

      - name: Wait for container to be healthy
        run: |
          echo "Waiting for container to start..."
          sleep 10

      - name: Check container status
        run: |
          docker ps
          echo "Checking API health..."
          curl -f http://localhost:3000/redis/health || exit 1

      - name: Show container logs
        if: always()
        run: |
          cd deploy
          docker compose logs --tail=50
