name: PR Slack Notify
on:
  pull_request:
    types: [opened, reopened, synchronize] # PR ìƒì„±, ì¬ì˜¤í”ˆ, ì»¤ë°‹ í‘¸ì‹œ ì‹œ
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR to Slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "ğŸ”” *ìƒˆ PR ìƒì„±ë¨* <#${{ github.event.pull_request.number }}|${{ github.event.pull_request.title }}> by <${{ github.actor }}|${{ github.actor }}> :boostcamp:",
              "username": "PR Bot",
              "icon_emoji": ":github:"
            }
